SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
DROP VIEW IF EXISTS dbo.FileCount_Staging
GO

DROP TABLE IF EXISTS dbo.Staging;
GO

CREATE TABLE [dbo].[Staging](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Timestamp] [datetime] NOT NULL,
	[Level] [nvarchar](10) NOT NULL,
	[Message] [nvarchar](max) NOT NULL,
	[SourceFile] [nvarchar](50) NOT NULL
	-- [TimeZone] [nvarchar](10) NOT NULL,
	-- [HostIP] [nvarchar](20) NOT NULL,
	-- [HostName] [nvarchar](50) NOT NULL,
	-- [Protocol] [nvarchar](3) NOT NULL,
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

-- Add indexes
ALTER TABLE [dbo].[Staging] ADD PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [IX_Level] ON [dbo].[Staging]
(
	[Level] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [IX_SourceFile] ON [dbo].[Staging]
(
	[SourceFile] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


-- Enable Compression 
ALTER TABLE [dbo].[Staging] REBUILD PARTITION = ALL
WITH 
(
	DATA_COMPRESSION = PAGE
)
GO

